// Generated by @bunwire/vite. Do not edit.
export interface BunwireRequestContract {}
export interface BunwireMessageContract {}
export interface BunwireClient {}
export const BUNWIRE_CLIENT_HASH = "317138df9154f282096ee2e095a34abddd8062a38ca868e42c4908b2d12b87be";
