// Generated by @bunwire/vite. Do not edit.
declare module "virtual:bunwire/registry" {
  export const applicationRegistry: import("@bunwire/core").RuntimeRegistry;
  export const BUNWIRE_REGISTRY_HASH: "ceee3c58e97236f8518c244743f25193d6b3731d08e7a47fd3abae6d113afe96";
  export default applicationRegistry;
}

declare module "virtual:bunwire/client" {
  export interface BunwireRequestContract {}
  export interface BunwireMessageContract {}
  export interface BunwireClient {}
  export const BUNWIRE_CLIENT_HASH: "317138df9154f282096ee2e095a34abddd8062a38ca868e42c4908b2d12b87be";
}
