// Generated by @bunwire/vite. Do not edit.
import { createElectrobunClient as __bunwire_create_client } from "@bunwire/electrobun";
import type { ElectrobunClientSchema as __bunwire_client_schema } from "@bunwire/electrobun";
import type { UserController as __bunwire_owner_0 } from "../src/bun/application.js";

type __bunwire_method_0 = InstanceType<typeof __bunwire_owner_0>["deleted"];
type __bunwire_method_1 = InstanceType<typeof __bunwire_owner_0>["get"];

type __bunwire_drop<Values extends readonly unknown[], Count extends number, Seen extends readonly unknown[] = []> = Seen['length'] extends Count ? Values : Values extends readonly [unknown, ...infer Rest] ? __bunwire_drop<Rest, Count, [...Seen, unknown]> : [];

export interface BunwireRequestContract {
  "users/get": (argument0: Parameters<__bunwire_method_1>[0], argument1?: Parameters<__bunwire_method_1>[4]) => Awaited<ReturnType<__bunwire_method_1>>;
}

export interface BunwireMessageContract {
  "users/deleted": (argument0: Parameters<__bunwire_method_0>[0]) => void;
}

export type BunwireClientSchema = __bunwire_client_schema<BunwireRequestContract, BunwireMessageContract>;

export interface BunwireClient {
  request<Method extends keyof BunwireRequestContract>(method: Method, ...args: Parameters<BunwireRequestContract[Method]>): Promise<ReturnType<BunwireRequestContract[Method]>>;
  message<Method extends keyof BunwireMessageContract>(method: Method, ...args: Parameters<BunwireMessageContract[Method]>): void;
}

export type BunwireClientTransport = Parameters<typeof __bunwire_create_client>[0];

export function createBunwireClient(transport: BunwireClientTransport): BunwireClient {
  return __bunwire_create_client(transport) as BunwireClient;
}
export const BUNWIRE_CLIENT_HASH = "16942905db21ec43d36575a502557738f6134e0ed9353678704611d01f39ecb9";
