// Generated by @bunwire/vite. Do not edit.
import { createParameterResolverId, defineManagedMethodPlan, defineRuntimeRegistry } from "@bunwire/core";
import { CACHE as __bunwire_import_8 } from "../src/bun/application.js";
import { CacheProvider as __bunwire_import_0 } from "../src/bun/application.js";
import { DatabaseService as __bunwire_import_2 } from "../src/bun/application.js";
import { UserController as __bunwire_import_4 } from "../src/bun/application.js";
import { UserService as __bunwire_import_6 } from "../src/bun/application.js";
import { requestLoggingMiddleware as __bunwire_import_9 } from "../src/bun/application.js";
import { Controller as __bunwire_import_5 } from "@bunwire/core";
import { Provider as __bunwire_import_1 } from "@bunwire/core";
import { Service as __bunwire_import_3 } from "@bunwire/core";
import { Message as __bunwire_import_10 } from "@bunwire/electrobun";
import { Route as __bunwire_import_7 } from "@bunwire/electrobun";

export const applicationRegistry = defineRuntimeRegistry({
  classes: [
    { kind: __bunwire_import_1.definition.kind, target: __bunwire_import_0, data: { "constructorPolicy": "zero-arguments", "lifecycleHooks": ["register", "boot"] }, scope: "singleton", dependencies: [] },
    { kind: __bunwire_import_3.definition.kind, target: __bunwire_import_2, data: { "scope": "singleton" }, scope: "singleton", dependencies: [] },
    { kind: __bunwire_import_5.definition.kind, target: __bunwire_import_4, data: { "prefix": "users" }, scope: "singleton", dependencies: [{ index: 0, token: __bunwire_import_6 }] },
    { kind: __bunwire_import_3.definition.kind, target: __bunwire_import_6, data: { "scope": "singleton" }, scope: "singleton", dependencies: [{ index: 0, token: __bunwire_import_2 }] },
  ],
  providers: [
    __bunwire_import_0,
  ],
  methods: [
    defineManagedMethodPlan({ kind: __bunwire_import_7.definition.kind, ownerKind: __bunwire_import_5.definition.kind, target: __bunwire_import_4, method: "get", data: { "path": "get" }, parameters: [{ source: "transport", methodIndex: 0, argumentIndex: 0, optional: false, rest: false }, { source: "container", methodIndex: 1, token: __bunwire_import_6 }, { source: "container", methodIndex: 2, token: __bunwire_import_8 }, { source: "resolver", methodIndex: 3, resolverId: createParameterResolverId("electrobun.window"), data: undefined }, { source: "transport", methodIndex: 4, argumentIndex: 1, optional: true, rest: false }], middleware: [__bunwire_import_9] }),
    defineManagedMethodPlan({ kind: __bunwire_import_10.definition.kind, ownerKind: __bunwire_import_5.definition.kind, target: __bunwire_import_4, method: "deleted", data: { "path": "deleted" }, parameters: [{ source: "transport", methodIndex: 0, argumentIndex: 0, optional: false, rest: false }, { source: "resolver", methodIndex: 1, resolverId: createParameterResolverId("electrobun.context"), data: undefined }], middleware: [] }),
  ],
});
export const BUNWIRE_REGISTRY_HASH = "47a2e942d96a337d3bd340062861e4632860d5a601b1ef828453c293b2855452";
export default applicationRegistry;
