// Generated by @bunwire/vite. Do not edit.
import { createParameterResolverId, defineManagedMethodPlan, defineMiddlewareAttachment, defineMiddlewareDefinition, defineRuntimeRegistry } from "@bunwire/core";
import { CACHE as __bunwire_import_9 } from "../src/bun/application.js";
import { CacheProvider as __bunwire_import_0 } from "../src/bun/application.js";
import { DatabaseService as __bunwire_import_2 } from "../src/bun/application.js";
import { RequestLoggingMiddleware as __bunwire_import_4 } from "../src/bun/application.js";
import { UserController as __bunwire_import_6 } from "../src/bun/application.js";
import { UserService as __bunwire_import_5 } from "../src/bun/application.js";
import { Controller as __bunwire_import_7 } from "@bunwire/core";
import { Provider as __bunwire_import_1 } from "@bunwire/core";
import { Service as __bunwire_import_3 } from "@bunwire/core";
import { Message as __bunwire_import_10 } from "@bunwire/electrobun";
import { Route as __bunwire_import_8 } from "@bunwire/electrobun";

export const applicationRegistry = defineRuntimeRegistry({
  classes: [
    { kind: __bunwire_import_1.definition.kind, target: __bunwire_import_0, data: { "constructorPolicy": "zero-arguments", "lifecycleHooks": ["register", "boot"] }, scope: "singleton", dependencies: [] },
    { kind: __bunwire_import_3.definition.kind, target: __bunwire_import_2, data: { "scope": "singleton" }, scope: "singleton", dependencies: [] },
    defineMiddlewareDefinition({ target: __bunwire_import_4, data: { "alias": "request-logger", "only": ["request"] }, dependencies: [{ index: 0, token: __bunwire_import_5 }] }),
    { kind: __bunwire_import_7.definition.kind, target: __bunwire_import_6, data: { "prefix": "users" }, scope: "singleton", dependencies: [{ index: 0, token: __bunwire_import_5 }] },
    { kind: __bunwire_import_3.definition.kind, target: __bunwire_import_5, data: { "scope": "singleton" }, scope: "singleton", dependencies: [{ index: 0, token: __bunwire_import_2 }] },
  ],
  providers: [
    __bunwire_import_0,
  ],
  methods: [
    defineManagedMethodPlan({ kind: __bunwire_import_8.definition.kind, ownerKind: __bunwire_import_7.definition.kind, target: __bunwire_import_6, method: "get", data: { "path": "get" }, parameters: [{ source: "transport", methodIndex: 0, argumentIndex: 0, optional: false, rest: false }, { source: "container", methodIndex: 1, token: __bunwire_import_5 }, { source: "container", methodIndex: 2, token: __bunwire_import_9 }, { source: "resolver", methodIndex: 3, resolverId: createParameterResolverId("electrobun.window"), data: undefined }, { source: "transport", methodIndex: 4, argumentIndex: 1, optional: true, rest: false }], middleware: [defineMiddlewareAttachment(__bunwire_import_4, [])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_10.definition.kind, ownerKind: __bunwire_import_7.definition.kind, target: __bunwire_import_6, method: "deleted", data: { "path": "deleted" }, parameters: [{ source: "transport", methodIndex: 0, argumentIndex: 0, optional: false, rest: false }, { source: "resolver", methodIndex: 1, resolverId: createParameterResolverId("electrobun.context"), data: undefined }], middleware: [] }),
  ],
  events: [
  ],
  eventAliases: [
  ],
});
export const BUNWIRE_REGISTRY_HASH = "c937fe4132497e9cc53af1cfe2df44f805afc5768c5d563eeea2fd111c0ca6eb";
export default applicationRegistry;
