// Generated by @bunwire/vite. Do not edit.
declare module "virtual:bunwire/registry" {
  export const applicationRegistry: import("@bunwire/core").RuntimeRegistry;
  export const BUNWIRE_REGISTRY_HASH: "2e20e579ed406e154baa437d79d504e271951324ed49491621805a957bfafeaa";
  export default applicationRegistry;
}

declare module "virtual:bunwire/client" {
  type __bunwire_method_0 = InstanceType<typeof import("../src/bun/application.js").UserController>["deleted"];
  type __bunwire_method_1 = InstanceType<typeof import("../src/bun/application.js").UserController>["get"];

  type __bunwire_drop<Values extends readonly unknown[], Count extends number, Seen extends readonly unknown[] = []> = Seen['length'] extends Count ? Values : Values extends readonly [unknown, ...infer Rest] ? __bunwire_drop<Rest, Count, [...Seen, unknown]> : [];

  export interface BunwireRequestContract {
    "users/get": (argument0: Parameters<__bunwire_method_1>[0], argument1?: Parameters<__bunwire_method_1>[4]) => Awaited<ReturnType<__bunwire_method_1>>;
  }

  export interface BunwireMessageContract {
    "users/deleted": (argument0: Parameters<__bunwire_method_0>[0]) => void;
  }

  export type BunwireClientSchema = import("@bunwire/electrobun").ElectrobunClientSchema<BunwireRequestContract, BunwireMessageContract>;

  export interface BunwireClient {
    request<Method extends keyof BunwireRequestContract>(method: Method, ...args: Parameters<BunwireRequestContract[Method]>): Promise<ReturnType<BunwireRequestContract[Method]>>;
    message<Method extends keyof BunwireMessageContract>(method: Method, ...args: Parameters<BunwireMessageContract[Method]>): void;
  }

  export type BunwireClientTransport = Parameters<typeof import("@bunwire/electrobun").createElectrobunClient>[0];
  export function createBunwireClient(transport: BunwireClientTransport): BunwireClient;
  export const BUNWIRE_CLIENT_HASH: "16942905db21ec43d36575a502557738f6134e0ed9353678704611d01f39ecb9";
}
