// Generated by @bunwire/vite. Do not edit.
import { defineManagedClassAttachment, createParameterResolverId, defineManagedMethodPlan, defineMiddlewareDefinition, defineEventAlias, defineEventDefinition, defineListenerDefinition, defineRuntimeRegistry } from "@bunwire/core";
import { DemoProgress as __bunwire_import_0 } from "../src/work.js";
import { Greet as __bunwire_import_5 } from "../src/work.js";
import { SendWelcome as __bunwire_import_2 } from "../src/work.js";
import { Welcome as __bunwire_import_3 } from "../src/work.js";
import { AuthenticateMiddleware as __bunwire_import_7 } from "@bunwire/bun";
import { AuthorizeMiddleware as __bunwire_import_9 } from "@bunwire/bun";
import { BUN_JOB_CONTEXT as __bunwire_import_1 } from "@bunwire/bun";
import { BUN_JOB_HANDLE_KIND as __bunwire_import_11 } from "@bunwire/bun";
import { CsrfMiddleware as __bunwire_import_10 } from "@bunwire/bun";
import { GuestMiddleware as __bunwire_import_8 } from "@bunwire/bun";
import { Job as __bunwire_import_6 } from "@bunwire/bun";
import { Queue as __bunwire_import_12 } from "@bunwire/bun";
import { Service as __bunwire_import_4 } from "@bunwire/core";

const __bunwire_listener_0 = defineListenerDefinition({ target: __bunwire_import_2, event: __bunwire_import_3, dependencies: [{ index: 0, token: __bunwire_import_0 }, { index: 1, token: __bunwire_import_1 }] });
const __bunwire_event_0 = defineEventDefinition({ target: __bunwire_import_3, listeners: [__bunwire_listener_0] });

export const applicationRegistry = defineRuntimeRegistry({
  classAttachments: [
    defineManagedClassAttachment({ target: __bunwire_import_2, definition: __bunwire_import_12.definition, data: { "backoff": [], "id": "example.worker-welcome", "queue": "default", "tries": 2 } }),
  ],
  classes: [
    { kind: __bunwire_import_4.definition.kind, target: __bunwire_import_0, data: { "scope": "singleton" }, scope: "singleton", dependencies: [] },
    { kind: __bunwire_import_6.definition.kind, target: __bunwire_import_5, data: { "backoff": [20], "id": "example.worker-greeting", "queue": "default", "tries": 2 }, scope: "transient", dependencies: [{ index: 0, token: __bunwire_import_0 }, { index: 1, token: __bunwire_import_1 }] },
    __bunwire_listener_0,
    __bunwire_event_0,
    defineMiddlewareDefinition({ target: __bunwire_import_7, data: { "alias": "auth" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_8, data: { "alias": "guest" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_9, data: { "alias": "can" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_10, data: { "alias": "csrf" }, dependencies: [] }),
  ],
  providers: [
  ],
  methods: [
    defineManagedMethodPlan({ kind: __bunwire_import_11, ownerKind: __bunwire_import_6.definition.kind, target: __bunwire_import_5, method: "handle", data: undefined, parameters: [{ source: "transport", methodIndex: 0, argumentIndex: 0, optional: false, rest: false }], middleware: [] }),
    __bunwire_listener_0.handle,
  ],
  events: [
    __bunwire_event_0,
  ],
  eventAliases: [
  ],
});
export const BUNWIRE_REGISTRY_HASH = "50e0ce1057a9c89788be6354dc8c70e7dd5dee9088ba6c0b9b4cc673ac2dddec";
export default applicationRegistry;
