// Generated by @bunwire/vite. Do not edit.
declare module "virtual:bunwire/registry" {
  export const applicationRegistry: import("@bunwire/core").RuntimeRegistry;
  export const BUNWIRE_REGISTRY_HASH: "50e0ce1057a9c89788be6354dc8c70e7dd5dee9088ba6c0b9b4cc673ac2dddec";
  export default applicationRegistry;
}

declare module "virtual:bunwire/client" {
  export interface BunwireRequestContract {}
  export interface BunwireMessageContract {}
  export interface BunwireClient {}
  export const BUNWIRE_CLIENT_HASH: "317138df9154f282096ee2e095a34abddd8062a38ca868e42c4908b2d12b87be";
}
