import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { generateCallerContractModule } from "./caller-contract-generator.js";
import {
  analyzeBunwireApplication,
  type AnalyzeBunwireApplicationOptions,
  type AnalyzedBunwireApplication,
} from "./discovery.js";
import { generateRuntimeRegistryModule } from "./registry-generator.js";

export interface BunwireGeneratedArtifactPaths {
  readonly registry: string;
  readonly client: string;
  readonly declarations: string;
}

export interface GenerateBunwireArtifactsOptions extends AnalyzeBunwireApplicationOptions {
  readonly generatedModulePath?: string;
  readonly generatedClientModulePath?: string;
  readonly generatedDeclarationsPath?: string;
}

export interface GeneratedBunwireArtifacts {
  readonly paths: BunwireGeneratedArtifactPaths;
  readonly registryHash: string;
  readonly clientHash: string;
  readonly changedPaths: readonly string[];
}

export function resolveGeneratedArtifactPaths(
  root: string,
  options: Pick<
  GenerateBunwireArtifactsOptions,
  "generatedModulePath" | "generatedClientModulePath" | "generatedDeclarationsPath"
  >,
): BunwireGeneratedArtifactPaths {
  return Object.freeze({
    registry: path.resolve(options.generatedModulePath ?? path.join(root, ".bunwire", "registry.ts")),
    client: path.resolve(options.generatedClientModulePath ?? path.join(root, ".bunwire", "client.ts")),
    declarations: path.resolve(
      options.generatedDeclarationsPath ?? path.join(root, ".bunwire", "virtual-modules.d.ts"),
    ),
  });
}

async function writeIfChanged(filePath: string, contents: string): Promise<boolean> {
  let current: string | undefined;
  try {
    current = await readFile(filePath, "utf8");
  } catch {}
  if (current === contents) return false;
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, contents, "utf8");
  return true;
}

export async function generateBunwireArtifactsFromApplication(
  application: AnalyzedBunwireApplication,
  options: GenerateBunwireArtifactsOptions = {},
): Promise<GeneratedBunwireArtifacts> {
  const paths = resolveGeneratedArtifactPaths(application.config.root, options);
  const registry = generateRuntimeRegistryModule({
    analysis: application.analysis,
    extensions: application.extensions,
    modulePath: paths.registry,
  });
  const client = generateCallerContractModule({
    analysis: application.analysis,
    extensions: application.extensions,
    modulePath: paths.client,
    declarationModulePath: paths.declarations,
  });
  const declarations = [
    "// Generated by @bunwire/vite. Do not edit.",
    registry.declarationCode.trimEnd(),
    "",
    client.declarationCode.trimEnd(),
    "",
  ].join("\n");
  const outputs = [
    [paths.registry, registry.code],
    [paths.client, client.code],
    [paths.declarations, declarations],
  ] as const;
  const changedPaths: string[] = [];
  for (const [filePath, contents] of outputs) {
    if (await writeIfChanged(filePath, contents)) changedPaths.push(filePath);
  }
  return Object.freeze({
    paths,
    registryHash: registry.hash,
    clientHash: client.hash,
    changedPaths: Object.freeze(changedPaths),
  });
}

export async function generateBunwireArtifacts(
  options: GenerateBunwireArtifactsOptions = {},
): Promise<GeneratedBunwireArtifacts> {
  const application = await analyzeBunwireApplication(options);
  return generateBunwireArtifactsFromApplication(application, options);
}
