import { createHash } from "node:crypto";
import { readdir } from "node:fs/promises";
import path from "node:path";
import { BunwireCompilerError } from "./diagnostics.js";
import type { ResolvedBunwireConfig, ResolvedBunwirePagesConfig } from "./config.js";

export interface DiscoveredBunwirePage {
  readonly name: string;
  readonly filePath: string;
  readonly moduleId: string;
}

export interface GeneratedBunwirePageModule {
  readonly code: string;
  readonly declarationCode: string;
  readonly manifestCode: string;
  readonly hash: string;
  readonly pages: readonly DiscoveredBunwirePage[];
}

export interface BunwirePageAssetManifest {
  readonly protocol: 1;
  readonly mode: "development" | "production";
  readonly components: readonly string[];
  readonly entry: string;
  readonly styles?: readonly string[];
  readonly version?: string;
  readonly assetRoot?: string;
  readonly assets?: readonly string[];
}

function posix(value: string): string { return value.replaceAll(path.sep, "/"); }

async function collect(directory: string, extensions: ReadonlySet<string>, files: string[]): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true });
  entries.sort((left, right) => left.name.localeCompare(right.name));
  for (const entry of entries) {
    const target = path.join(directory, entry.name);
    if (entry.isSymbolicLink()) throw new BunwireCompilerError("CONFIG_INVALID", `Bunwire page root cannot contain filesystem links; found "${target}".`, { filePath: target });
    if (entry.isDirectory()) await collect(target, extensions, files);
    else if (entry.isFile() && extensions.has(path.extname(entry.name))) files.push(target);
  }
}

export async function discoverBunwirePages(
  root: string,
  config: ResolvedBunwirePagesConfig,
): Promise<readonly DiscoveredBunwirePage[]> {
  const files: string[] = [];
  await collect(config.root, new Set(config.extensions), files);
  if (files.length === 0) throw new BunwireCompilerError("CONFIG_INVALID", `Bunwire pages root "${config.root}" contains no configured page components.`, { filePath: config.root });
  const names = new Map<string, string>();
  const pages = files.map((filePath) => {
    const relative = posix(path.relative(config.root, filePath));
    const name = relative.slice(0, -path.extname(relative).length);
    if (!name || name.split("/").some((segment) => !/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(segment))) {
      throw new BunwireCompilerError("CONFIG_INVALID", `Bunwire page path "${relative}" does not produce a valid component name.`, { filePath });
    }
    const existing = names.get(name);
    if (existing) throw new BunwireCompilerError("CONFIG_INVALID", `Bunwire page component name "${name}" is produced by both "${existing}" and "${filePath}".`, { filePath });
    names.set(name, filePath);
    return Object.freeze({ name, filePath, moduleId: `/${posix(path.relative(root, filePath))}` });
  });
  return Object.freeze(pages.sort((left, right) => left.name.localeCompare(right.name)));
}

function quote(value: string): string { return JSON.stringify(value); }

export function renderBunwirePageManifest(manifest: BunwirePageAssetManifest): string {
  return `// Generated by @bunwire/vite. Do not edit.\nexport const pageManifest = Object.freeze(${JSON.stringify(manifest, null, 2)});\nexport default pageManifest;\n`;
}

export async function generateBunwirePageModule(
  config: ResolvedBunwireConfig,
): Promise<GeneratedBunwirePageModule | undefined> {
  if (!config.pages) return undefined;
  const pages = await discoverBunwirePages(config.root, config.pages);
  const catalog = pages.map((entry) => `  ${quote(entry.name)}: () => import(${quote(entry.moduleId)}),`).join("\n");
  const names = pages.map(({ name }) => name);
  const entryPath = `/${posix(path.relative(config.root, config.pages.entry))}`;
  const entry = new URL(entryPath, config.pages.devServer).href;
  const hash = createHash("sha256").update(JSON.stringify({ names, entryPath })).digest("hex");
  const code = `// Generated by @bunwire/vite. Do not edit.\nconst pages = Object.freeze({\n${catalog}\n});\nexport const pageNames = Object.freeze(${JSON.stringify(names)});\nexport function resolvePage(name) {\n  const loader = pages[name];\n  if (!loader) throw new Error(\`Unknown Bunwire page component \${JSON.stringify(name)}.\`);\n  return loader();\n}\nexport default resolvePage;\n`;
  const declarationCode = `declare module "virtual:bunwire/pages" {\n  export const pageNames: readonly string[];\n  export function resolvePage<Component = unknown>(name: string): Promise<{ readonly default: Component }>;\n  export default resolvePage;\n}`;
  const manifest: BunwirePageAssetManifest = { protocol: 1, mode: "development", components: names, entry };
  const manifestCode = renderBunwirePageManifest(manifest);
  return Object.freeze({ code, declarationCode, manifestCode, hash, pages });
}
