// Generated by @bunwire/vite. Do not edit.
export const pageManifest = Object.freeze({
  "protocol": 1,
  "mode": "production",
  "components": [
    "Dashboard",
    "Home"
  ],
  "entry": "/assets/frontend-DWTa3m3A.js",
  "version": "bb48d1f8e0c6383e64bb4d58ea78f9ad943cae469732d47f84f03b9cfd0ca946",
  "assetRoot": "dist/client",
  "assets": [
    "/assets/Dashboard-DoYsnAYq.js",
    "/assets/Home-LjUaIl4b.js",
    "/assets/frontend-DWTa3m3A.js"
  ]
});
export default pageManifest;
