// Generated by @bunwire/vite. Do not edit.
import { createParameterResolverId, defineManagedMethodPlan, defineMiddlewareAttachment, defineMiddlewareDefinition, defineRuntimeRegistry } from "@bunwire/core";
import { HomeController as __bunwire_import_0 } from "../src/home-controller.js";
import { ExampleGuardMiddleware as __bunwire_import_2 } from "../src/http-middleware.js";
import { ExampleHttpMiddleware as __bunwire_import_3 } from "../src/http-middleware.js";
import { Get as __bunwire_import_4 } from "@bunwire/bun";
import { Post as __bunwire_import_5 } from "@bunwire/bun";
import { Controller as __bunwire_import_1 } from "@bunwire/core";

export const applicationRegistry = defineRuntimeRegistry({
  classes: [
    { kind: __bunwire_import_1.definition.kind, target: __bunwire_import_0, data: { "prefix": "/api" }, scope: "singleton", dependencies: [] },
    defineMiddlewareDefinition({ target: __bunwire_import_2, data: { "alias": "example-guard" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_3, data: { "alias": "example-http", "include": ["/api/**"], "only": ["GET", "POST"] }, dependencies: [] }),
  ],
  providers: [
  ],
  methods: [
    defineManagedMethodPlan({ kind: __bunwire_import_4.definition.kind, ownerKind: __bunwire_import_1.definition.kind, target: __bunwire_import_0, method: "index", data: { "method": "GET", "path": "/" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_3, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_5.definition.kind, ownerKind: __bunwire_import_1.definition.kind, target: __bunwire_import_0, method: "echo", data: { "method": "POST", "path": "/echo/:id" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_3, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_4.definition.kind, ownerKind: __bunwire_import_1.definition.kind, target: __bunwire_import_0, method: "blocked", data: { "method": "GET", "path": "/blocked" }, parameters: [], middleware: [defineMiddlewareAttachment(__bunwire_import_3, ["example"]), defineMiddlewareAttachment(__bunwire_import_2, ["deny"])] }),
  ],
  events: [
  ],
  eventAliases: [
  ],
});
export const BUNWIRE_REGISTRY_HASH = "c7f37532351ab2e3a78e1f81e218f1c0bec7a6300a8c39fa7e0e9333522bd438";
export default applicationRegistry;
