// Generated by @bunwire/vite. Do not edit.
import { defineManagedClassAttachment, createParameterResolverId, defineManagedMethodPlan, defineMiddlewareAttachment, defineMiddlewareDefinition, defineEventAlias, defineEventDefinition, defineListenerDefinition, defineRuntimeRegistry } from "@bunwire/core";
import { EchoNormalizer as __bunwire_import_5 } from "../src/echo-request.js";
import { EchoRequest as __bunwire_import_7 } from "../src/echo-request.js";
import { ExampleActionRecorded as __bunwire_import_2 } from "../src/events.js";
import { ExampleEventAudit as __bunwire_import_0 } from "../src/events.js";
import { ExampleQueuedAudit as __bunwire_import_3 } from "../src/events.js";
import { QueueExampleAction as __bunwire_import_4 } from "../src/events.js";
import { RecordExampleAction as __bunwire_import_1 } from "../src/events.js";
import { HomeController as __bunwire_import_9 } from "../src/home-controller.js";
import { ExampleGuardMiddleware as __bunwire_import_11 } from "../src/http-middleware.js";
import { ExampleHttpMiddleware as __bunwire_import_12 } from "../src/http-middleware.js";
import { ExampleJobAudit as __bunwire_import_13 } from "../src/jobs.js";
import { RecordExampleJob as __bunwire_import_14 } from "../src/jobs.js";
import { AuthenticateMiddleware as __bunwire_import_16 } from "@bunwire/bun";
import { AuthorizeMiddleware as __bunwire_import_18 } from "@bunwire/bun";
import { BUN_JOB_HANDLE_KIND as __bunwire_import_24 } from "@bunwire/bun";
import { BUN_QUEUE_MANAGER as __bunwire_import_21 } from "@bunwire/bun";
import { CsrfMiddleware as __bunwire_import_19 } from "@bunwire/bun";
import { Get as __bunwire_import_23 } from "@bunwire/bun";
import { GuestMiddleware as __bunwire_import_17 } from "@bunwire/bun";
import { Job as __bunwire_import_15 } from "@bunwire/bun";
import { Post as __bunwire_import_20 } from "@bunwire/bun";
import { Queue as __bunwire_import_25 } from "@bunwire/bun";
import { Request as __bunwire_import_8 } from "@bunwire/bun";
import { Controller as __bunwire_import_10 } from "@bunwire/core";
import { EventDispatcher as __bunwire_import_22 } from "@bunwire/core";
import { Service as __bunwire_import_6 } from "@bunwire/core";

const __bunwire_listener_0 = defineListenerDefinition({ target: __bunwire_import_1, event: __bunwire_import_2, dependencies: [{ index: 0, token: __bunwire_import_0 }] });
const __bunwire_listener_1 = defineListenerDefinition({ target: __bunwire_import_4, event: __bunwire_import_2, dependencies: [{ index: 0, token: __bunwire_import_3 }] });
const __bunwire_event_0 = defineEventDefinition({ target: __bunwire_import_2, alias: "example.action-recorded", listeners: [__bunwire_listener_0, __bunwire_listener_1] });

export const applicationRegistry = defineRuntimeRegistry({
  classAttachments: [
    defineManagedClassAttachment({ target: __bunwire_import_4, definition: __bunwire_import_25.definition, data: { "backoff": [], "id": "example.queued-action", "queue": "default", "tries": 1 } }),
  ],
  classes: [
    { kind: __bunwire_import_6.definition.kind, target: __bunwire_import_5, data: { "scope": "singleton" }, scope: "singleton", dependencies: [] },
    { kind: __bunwire_import_8.definition.kind, target: __bunwire_import_7, data: { "type": "request" }, scope: "singleton", dependencies: [{ index: 0, token: __bunwire_import_5 }] },
    __bunwire_event_0,
    { kind: __bunwire_import_6.definition.kind, target: __bunwire_import_0, data: { "scope": "singleton" }, scope: "singleton", dependencies: [] },
    { kind: __bunwire_import_6.definition.kind, target: __bunwire_import_3, data: { "scope": "singleton" }, scope: "singleton", dependencies: [] },
    __bunwire_listener_1,
    __bunwire_listener_0,
    { kind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, data: { "prefix": "/api" }, scope: "singleton", dependencies: [] },
    defineMiddlewareDefinition({ target: __bunwire_import_11, data: { "alias": "example-guard" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_12, data: { "alias": "example-http", "include": ["/api/**"], "only": ["GET", "POST"] }, dependencies: [] }),
    { kind: __bunwire_import_6.definition.kind, target: __bunwire_import_13, data: { "scope": "singleton" }, scope: "singleton", dependencies: [] },
    { kind: __bunwire_import_15.definition.kind, target: __bunwire_import_14, data: { "backoff": [], "id": "example.record-action", "queue": "audit", "tries": 1 }, scope: "transient", dependencies: [{ index: 0, token: __bunwire_import_13 }] },
    defineMiddlewareDefinition({ target: __bunwire_import_16, data: { "alias": "auth" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_17, data: { "alias": "guest" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_18, data: { "alias": "can" }, dependencies: [] }),
    defineMiddlewareDefinition({ target: __bunwire_import_19, data: { "alias": "csrf" }, dependencies: [] }),
  ],
  providers: [
  ],
  methods: [
    defineManagedMethodPlan({ kind: __bunwire_import_20.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "recordJob", data: { "method": "POST", "path": "/jobs/:id" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }, { source: "container", methodIndex: 1, token: __bunwire_import_21 }, { source: "container", methodIndex: 2, token: __bunwire_import_13 }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_20.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "recordEvent", data: { "method": "POST", "path": "/events/:id" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }, { source: "container", methodIndex: 1, token: __bunwire_import_22 }, { source: "container", methodIndex: 2, token: __bunwire_import_0 }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "index", data: { "method": "GET", "path": "/" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_20.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "echo", data: { "method": "POST", "path": "/echo/:id" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.form-request"), data: undefined, token: __bunwire_import_7 }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "blocked", data: { "method": "GET", "path": "/blocked" }, parameters: [], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"]), defineMiddlewareAttachment(__bunwire_import_11, ["deny"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "home", data: { "method": "GET", "path": "/home" }, parameters: [], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "pageHome", data: { "method": "GET", "path": "/page" }, parameters: [], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "pageDashboard", data: { "method": "GET", "path": "/page/dashboard" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "session", data: { "method": "GET", "path": "/session" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_20.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "updateSession", data: { "method": "POST", "path": "/session" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"]), defineMiddlewareAttachment(__bunwire_import_19, [])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "login", data: { "method": "GET", "path": "/login" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "account", data: { "method": "GET", "path": "/account" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"]), defineMiddlewareAttachment(__bunwire_import_16, [])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "dashboard", data: { "method": "GET", "path": "/dashboard" }, parameters: [], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"]), defineMiddlewareAttachment(__bunwire_import_16, []), defineMiddlewareAttachment(__bunwire_import_18, ["dashboard.view"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "post", data: { "method": "GET", "path": "/posts/:post" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"]), defineMiddlewareAttachment(__bunwire_import_16, []), defineMiddlewareAttachment(__bunwire_import_18, ["view", "post"])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_23.definition.kind, ownerKind: __bunwire_import_10.definition.kind, target: __bunwire_import_9, method: "logout", data: { "method": "GET", "path": "/logout" }, parameters: [{ source: "resolver", methodIndex: 0, resolverId: createParameterResolverId("bun.http-context"), data: undefined }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"]), defineMiddlewareAttachment(__bunwire_import_16, [])] }),
    defineManagedMethodPlan({ kind: __bunwire_import_24, ownerKind: __bunwire_import_15.definition.kind, target: __bunwire_import_14, method: "handle", data: undefined, parameters: [{ source: "transport", methodIndex: 0, argumentIndex: 0, optional: false, rest: false }], middleware: [defineMiddlewareAttachment(__bunwire_import_12, ["example"])] }),
    __bunwire_listener_0.handle,
    __bunwire_listener_1.handle,
  ],
  events: [
    __bunwire_event_0,
  ],
  eventAliases: [
    defineEventAlias("example.action-recorded", __bunwire_event_0),
  ],
});
export const BUNWIRE_REGISTRY_HASH = "a9f359e8fc4f02ada9e6f01192c62b5d31815659b7387d18b70c37516e6ed7bf";
export default applicationRegistry;
