// Generated by @bunwire/vite. Do not edit.
import { createParameterResolverId, defineManagedMethodPlan, defineRuntimeRegistry } from "@bunwire/core";

export const applicationRegistry = defineRuntimeRegistry({
  classes: [
  ],
  providers: [
  ],
  methods: [
  ],
  events: [
  ],
  eventAliases: [
  ],
});
export const BUNWIRE_REGISTRY_HASH = "09e10231818d01b9a6b6d2befe7718fd75f0083d8a88c7830fc975c57da01ddb";
export default applicationRegistry;
