// Generated by @bunwire/vite. Do not edit.
declare module "virtual:bunwire/registry" {
  export const applicationRegistry: import("@bunwire/core").RuntimeRegistry;
  export const BUNWIRE_REGISTRY_HASH: "09e10231818d01b9a6b6d2befe7718fd75f0083d8a88c7830fc975c57da01ddb";
  export default applicationRegistry;
}

declare module "virtual:bunwire/client" {
  export interface BunwireRequestContract {}
  export interface BunwireMessageContract {}
  export interface BunwireClient {}
  export const BUNWIRE_CLIENT_HASH: "317138df9154f282096ee2e095a34abddd8062a38ca868e42c4908b2d12b87be";
}
