// Generated by @bunwire/vite. Do not edit.
declare module "virtual:bunwire/registry" {
  export const applicationRegistry: import("@bunwire/core").RuntimeRegistry;
  export const BUNWIRE_REGISTRY_HASH: "a9f359e8fc4f02ada9e6f01192c62b5d31815659b7387d18b70c37516e6ed7bf";
  export default applicationRegistry;
}

declare module "virtual:bunwire/client" {
  export interface BunwireRequestContract {}
  export interface BunwireMessageContract {}
  export interface BunwireClient {}
  export const BUNWIRE_CLIENT_HASH: "317138df9154f282096ee2e095a34abddd8062a38ca868e42c4908b2d12b87be";
}

declare module "virtual:bunwire/pages" {
  export const pageNames: readonly string[];
  export function resolvePage<Component = unknown>(name: string): Promise<{ readonly default: Component }>;
  export default resolvePage;
}
