// Generated by @bunwire/vite. Do not edit.
declare module "virtual:bunwire/registry" {
  export const applicationRegistry: import("@bunwire/core").RuntimeRegistry;
  export const BUNWIRE_REGISTRY_HASH: "c7f37532351ab2e3a78e1f81e218f1c0bec7a6300a8c39fa7e0e9333522bd438";
  export default applicationRegistry;
}

declare module "virtual:bunwire/client" {
  export interface BunwireRequestContract {}
  export interface BunwireMessageContract {}
  export interface BunwireClient {}
  export const BUNWIRE_CLIENT_HASH: "317138df9154f282096ee2e095a34abddd8062a38ca868e42c4908b2d12b87be";
}
